### ISSUE TITLE
Features and improvements

### ISSUE THREAD

**Issue by realgooseman** [hankxdev/one-click-extensions-manager#116]
Hi @hankxdev & @fregante ,

Love the extension, but there are some features I would like to see :

- Ability to change the extension icon to white/black to better fit browser theme
- Ability to shorten or rename extension names so they take less width space
- Show extension's current version on hover
- Visual indicator/notification that an extension has a new update (something like [this](https://github.com/beaufortfrancois/extensions-update-notifier-chrome-extension))

> For the last feature, it would be nice to have because Chromium-based browsers don't notify of new updates nor they show which extension got updated.

**Comment by fregante** [comment]
> * Ability to change the extension icon to white/black to better fit browser theme

Not a bad idea. I'm not sure if it's worth an option though. Related:

- https://github.com/hankxdev/one-click-extensions-manager/issues/63

> * Ability to shorten or rename extension names so they take less width space

Not going to happen, sorry. You can make the window smaller

> * Show extension's current version on hover

The extension’s version is rarely important since they update automatically. You don't expect websites to show their current "version", and extensions are just… well… _website extensions_

> * Visual indicator/notification that an extension has a new update (something like [this](https://github.com/beaufortfrancois/extensions-update-notifier-chrome-extension))

That sounds useful but not as part of this. `one-click-extensions-manager` is only meant as a quick way to toggle extensions, nothing more.
