### ISSUE TITLE
[Question] Why doesnt the extension work when used from github?

### ISSUE THREAD

**Issue by inson1** [hankxdev/one-click-extensions-manager#121]
![image](https://github.com/hankxdev/one-click-extensions-manager/assets/75314629/0ffc031d-3f1f-49af-979e-080364f24a12)
![image](https://github.com/hankxdev/one-click-extensions-manager/assets/75314629/eecaf69e-e648-4528-94e1-8209e8216ffc)

**Comment by hankxdev** [comment]
it's because you are loading it without building it.

step by step：
- read https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management
- run `npm install`
- run `npm run watch`

load the `distribution.` folder, not the source folder into Chrome

**Comment by hankxdev** [comment]
should be fine.
