### ISSUE TITLE
The options should be always visible

### ISSUE THREAD

**Issue by muescha** [hankxdev/one-click-extensions-manager#32]
Current:

- i accidently managed to show more optionas (see screenshot) than just only the settings icon

Expected:

- when there is a wider screen (#31) then it can be visible always

![Bildschirmfoto 2019-11-30 um 05 59 24](https://user-images.githubusercontent.com/184316/69896105-ade9cb80-133b-11ea-84b5-4d35fb4f3493.png)

**Comment by fregante** [comment]
We do have a secondary view (#4) that is already wider (#31) so this could be the default there: wider and buttons always visible. But _not_ in the popup

**Comment by muescha** [comment]
ok - only at options menu ... 
but thanks for reply

**Comment by HangYang** [comment]
@fregante I was thinking of this too. you can see Michale found the option icons `accidently`. I think many users have same expeirence too.
So I think may be make it to show option icons when hovering on the items. like in the very old version would be better.

**Comment by fregante** [comment]
>  So I think may be make it to show option icons when hovering on the items. like in the very old version would be better.

What old version? It was never this way, I added these features as an "extra" (https://github.com/HangYang/one-click-extensions-manager/pull/19) because the this extension is about toggling features. That's it. 

This extension is great because it's simple and clean. The moment we add a bunch of icons that you rarely need it's no longer "simple and clean".

However since the options page is a _secondary view,_ we can leave them open there, but it's still not great-looking.

**Comment by HangYang** [comment]
ok, before that, when mouse hovering on each extensions, if it has option page, the icon would flip a bit, and clicking on the icon would go to the options page.
so I think, rather than right click to show these icons for all extensions, we can just show these icons for current one when hovering on it, so that user can know there are more options. it won't make the UI complecated.

**Comment by fregante** [comment]
There's only one problem with that: there's no visual indicator that that will happen.

If someone clicks in the empty area near the Settings icon (expecting to toggle the extension), suddenly it's filled by 3 additional icons and they will click one of the new icons (instead of toggling the extension as expected)

Being buttons that one needs rarely, I think they're fine being hidden the way they are now.

If discoverability is the problem, we can show a tooltip like we do for ctrl+z

**Comment by fregante** [comment]
Icons now shown by default in the options

<img width="427" alt="" src="https://user-images.githubusercontent.com/1402241/76848109-66804000-6843-11ea-8d60-2a868abdc6ab.png">

**Comment by muescha** [comment]
great :)
thx

**Comment by fregante** [comment]
@muescha Option added 🎉 in the upcoming version https://github.com/hankxdev/one-click-extensions-manager/releases/tag/23.3.19
